### Listando receitas por usuário
GET http://localhost:3333/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM2OTEzNTksImV4cCI6MTc2MzY5NDk1OX0.1XMI1z9MquhcRFFkzJ1BGVgZv82aKm7mwasdS251O5Y

### Listar receita por ID
GET http://localhost:3333/recipes/47ac1d47-3154-40b9-ba80-b616f72eb857
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM2OTEzNTksImV4cCI6MTc2MzY5NDk1OX0.1XMI1z9MquhcRFFkzJ1BGVgZv82aKm7mwasdS251O5Y

### Criar receita (POST)
POST http://localhost:3333/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM2OTEzNTksImV4cCI6MTc2MzY5NDk1OX0.1XMI1z9MquhcRFFkzJ1BGVgZv82aKm7mwasdS251O5Y

{
  "title": "doce",
  "category": "dessert",
  "userId": "5002f32a-6e78-4c0a-9bed-93577581fcdb",
  "ingredients": [
    {
      
    },
    {
      "name": "farinha",
      "type": "Dairy",
      "quantity": 200
    }
  ]
}

### Criar ingredientes da receita (POST)
POST http://localhost:3333/recipes/0ab9e0a7-521c-4ebc-acc3-40988b5b2db3/ingredients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM2OTEzNTksImV4cCI6MTc2MzY5NDk1OX0.1XMI1z9MquhcRFFkzJ1BGVgZv82aKm7mwasdS251O5Y

{
  "name": "oléo",
  "type": "Dairy",
  "quantity": 1
}

### Atualizar receita (PUT)
PUT http://localhost:3333/recipes/911a34b4-2c66-4d6d-8834-ca229c3af2a3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM2OTEzNTksImV4cCI6MTc2MzY5NDk1OX0.1XMI1z9MquhcRFFkzJ1BGVgZv82aKm7mwasdS251O5Y

{
  "title": "pudim"
}

### Deletar receita (DELETE)
DELETE http://localhost:3333/recipes/66b2499a-e4ef-4e60-b5a5-7e756b3eb945
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM2OTEzNTksImV4cCI6MTc2MzY5NDk1OX0.1XMI1z9MquhcRFFkzJ1BGVgZv82aKm7mwasdS251O5Y