### Listando receitas por usuário
GET http://localhost:3333/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjA2NjY2NjAsImV4cCI6MTc2MDY3MDI2MH0.O0Fyrt6Lt5_3eSNm47vp2oN20FZft3udp2pAy3E0jE0

### Listar receita por ID
GET http://localhost:3333/recipes/c9c03c1a-9312-4d9e-b9bb-7dc6cfa7e3b4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjA2NjY2NjAsImV4cCI6MTc2MDY3MDI2MH0.O0Fyrt6Lt5_3eSNm47vp2oN20FZft3udp2pAy3E0jE0

### Criar receita (POST)
POST http://localhost:3333/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjA2NjY2NjAsImV4cCI6MTc2MDY3MDI2MH0.O0Fyrt6Lt5_3eSNm47vp2oN20FZft3udp2pAy3E0jE0

{
  "title": "doce",
  "category": "dessert",
  "userId": "5002f32a-6e78-4c0a-9bed-93577581fcdb"
}

### Atualizar receita (PUT)
PUT http://localhost:3333/recipes/911a34b4-2c66-4d6d-8834-ca229c3af2a3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjA2NjY2NjAsImV4cCI6MTc2MDY3MDI2MH0.O0Fyrt6Lt5_3eSNm47vp2oN20FZft3udp2pAy3E0jE0

{
  "title": "pudim"
}

### Deletar receita (DELETE)
DELETE http://localhost:3333/recipes/911a34b4-2c66-4d6d-8834-ca229c3af2a3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjA2NjY2NjAsImV4cCI6MTc2MDY3MDI2MH0.O0Fyrt6Lt5_3eSNm47vp2oN20FZft3udp2pAy3E0jE0