### Listando receitas por usuário
GET http://localhost:3333/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

### Listar receita por ID
GET http://localhost:3333/recipes/37cbb205-caa2-4176-8d19-f0c68c35717f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

### Criar receita (POST)
POST http://localhost:3333/recipes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

{
  "title": "torta salgada",
  "category": "dessert"
}

### Criar ingredientes da receita (POST)
POST http://localhost:3333/recipes/37cbb205-caa2-4176-8d19-f0c68c35717f/ingredients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

{
  "name": "leite",
  "type": "dairy",
  "quantity": 1,
  "unit": "liter"
}

### Criar passos da receita (POST)
POST http://localhost:3333/recipes/37cbb205-caa2-4176-8d19-f0c68c35717f/steps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

{
  "step": 1,
  "description": "Separe todos os ingredientes"
}

### Atualizar receita (PATCH)
PATCH http://localhost:3333/recipes/37cbb205-caa2-4176-8d19-f0c68c35717f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

{
  "title": "torta doce"
}

### Atualizar ingredientes da receita (PATCH)
PATCH http://localhost:3333/recipes/858f1a08-7a77-4d98-a2f7-bf02169b926d/ingredients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

{
  "id": "e81bf5f6-4219-4375-9d08-c97a53e3c766"
}

### Atualizar steps da receita (PATCH)
PATCH http://localhost:3333/recipes/1588c215-4def-4fc3-aace-c5e3c6958f3a/steps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ

{
  "description": "Atualizado com sucesso"
}

### Deletar receita (DELETE)
DELETE http://localhost:3333/recipes/638671cf-e8fb-4f77-9ce6-746b4b8ce055
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNWI3NmZmNC04Y2YyLTQ0NWUtYTU2Mi1mNzUwODRmMzgxYWUiLCJlbWFpbCI6ImVkaWxhQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MjczOTI1LCJleHAiOjE3NjgyNzc1MjV9.mIV4zGbNchj2nSOoYu3BK6_xhpZ1bJnV3CuzxeY2GrQ