### Listando ingredientes por usuário
GET http://localhost:3333/ingredients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ4OTYyODgsImV4cCI6MTc2NDg5OTg4OH0.IJagRXTJuXRxyn6yoCtzb48RKRT5zIgwvBURCvSOMYw

### Listar ingrediente por ID
GET http://localhost:3333/ingredients/e81bf5f6-4219-4375-9d08-c97a53e3c766
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ4OTYyODgsImV4cCI6MTc2NDg5OTg4OH0.IJagRXTJuXRxyn6yoCtzb48RKRT5zIgwvBURCvSOMYw

### Criar ingrediente (POST)
POST http://localhost:3333/ingredients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ4OTYyODgsImV4cCI6MTc2NDg5OTg4OH0.IJagRXTJuXRxyn6yoCtzb48RKRT5zIgwvBURCvSOMYw

{
  "name": "farinha",
  "type": "dairy",
  "userId": "5002f32a-6e78-4c0a-9bed-93577581fcdb"
}

### Atualizar ingrediente (PUT)
PUT http://localhost:3333/ingredients/74f393ed-c6b0-4e84-90e1-52c109110a73
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ4OTYyODgsImV4cCI6MTc2NDg5OTg4OH0.IJagRXTJuXRxyn6yoCtzb48RKRT5zIgwvBURCvSOMYw

{
  "name": "milk"
}

### Deletar ingrediente (DELETE)
DELETE http://localhost:3333/ingredients/74f393ed-c6b0-4e84-90e1-52c109110a73
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ4OTYyODgsImV4cCI6MTc2NDg5OTg4OH0.IJagRXTJuXRxyn6yoCtzb48RKRT5zIgwvBURCvSOMYw