### Listando ingredientes por usuário
GET http://localhost:3333/ingredients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQwOTg3MDEsImV4cCI6MTc2NDEwMjMwMX0.Kho_7ULkL7QJWYdugSYN-0_rcSasy6Lez5snCWMrZcE

### Listar ingrediente por ID
GET http://localhost:3333/ingredients/8feeb154-dd71-45e4-a8fa-f94f7f954e9f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQwOTg3MDEsImV4cCI6MTc2NDEwMjMwMX0.Kho_7ULkL7QJWYdugSYN-0_rcSasy6Lez5snCWMrZcE

### Criar ingrediente (POST)
POST http://localhost:3333/ingredients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQwOTg3MDEsImV4cCI6MTc2NDEwMjMwMX0.Kho_7ULkL7QJWYdugSYN-0_rcSasy6Lez5snCWMrZcE

{
  "name": "leite",
  "type": "Dairy",
  "userId": "5002f32a-6e78-4c0a-9bed-93577581fcdb"
}

### Atualizar ingrediente (PUT)
PUT http://localhost:3333/ingredients/8feeb154-dd71-45e4-a8fa-f94f7f954e9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQwOTg3MDEsImV4cCI6MTc2NDEwMjMwMX0.Kho_7ULkL7QJWYdugSYN-0_rcSasy6Lez5snCWMrZcE

{
  "name": "milk"
}

### Deletar ingrediente (DELETE)
DELETE http://localhost:3333/ingredients/8feeb154-dd71-45e4-a8fa-f94f7f954e9f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQwOTg3MDEsImV4cCI6MTc2NDEwMjMwMX0.Kho_7ULkL7QJWYdugSYN-0_rcSasy6Lez5snCWMrZcE