### Deletar receita (DELETE)
DELETE http://localhost:3333/ingredients/44dbde10-8d16-4cb1-b266-006a83edb4a4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDAyZjMyYS02ZTc4LTRjMGEtOWJlZC05MzU3NzU4MWZjZGIiLCJlbWFpbCI6ImRpbGFAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjE3MDg5NTAsImV4cCI6MTc2MTcxMjU1MH0.3EITNRbiCeJlKMoaz5PAUa--zb2ngnUSB92dzE-3cIg