### Criar usuário (POST)
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Edilaine",
  "email": "edila@example.com",
  "password": "securepassword"
}

### Atualizar usuário (PATCH)
PATCH http://localhost:3333/users/5002f32a-6e78-4c0a-9bed-93577581fcdb
Content-Type: application/json

{
  "name": "Edilaine Santos"
}