export enum RecipeIngredientUnit {
  TEASPOON = 'teaspoon',
  TABLESPOON = 'tablespoon',
  CUP = 'cup',
  MILLILITER = 'milliliter',
  LITER = 'liter',
  GRAM = 'gram',
  KILOGRAM = 'kilogram',
  OUNCE = 'ounce',
  POUND = 'pound',
  UNIT = 'unit',
  SLICE = 'slice',
  PIECE = 'piece',
  PINCH = 'pinch',
  HANDFUL = 'handful',
  PACKAGE = 'package',
  CAN = 'can',
  BUNCH = 'bunch',
}
