export enum RecipeIngredientUnit {
  TEASPOON = 'Teaspoon',
  TABLESPOON = 'Tablespoon',
  CUP = 'Cup',
  MILLILITER = 'Milliliter',
  LITER = 'Liter',
  GRAM = 'Gram',
  KILOGRAM = 'Kilogram',
  OUNCE = 'Ounce',
  POUND = 'Pound',
  UNIT = 'Unit',
  SLICE = 'Slice',
  PIECE = 'Piece',
  PINCH = 'Pinch',
  HANDFUL = 'Handful',
  PACKAGE = 'Package',
  CAN = 'Can',
  BUNCH = 'Bunch',
}
